name: CI 

on:
  push:
    branches: [ "main" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build backend image
    
      run: docker build -t kush233/brain-app ./brain-app
    - name: Push to dockerhub
      run: docker push kush233/brain-backend:latest

    - name: Build frontend image
      run: docker build -t kush233/brain-backend ./brain-frontend
    - name: Push to dockerhub
      run: docker push kush233/brain-frontend:latest
    